# Generated by Django 3.2.4 on 2021-08-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('empleado_encargado', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dependiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc_empleado', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=24)),
                ('fecha_nacimiento', models.DateField()),
                ('relacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=24)),
                ('direccion', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('salario', models.IntegerField()),
                ('supervisor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='empleados_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc_empleado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=30)),
                ('localidad', models.CharField(max_length=30)),
                ('barrio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_persona', models.CharField(max_length=24)),
                ('nom_usuario', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('local', models.CharField(max_length=30)),
            ],
        ),
    ]
