# Generated by Django 3.2.4 on 2021-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rfc',
            field=models.IntegerField(),
        ),
    ]
