# Generated by Django 3.2.4 on 2021-08-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0003_auto_20210801_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='local',
            new_name='nom_dep',
        ),
        migrations.AddField(
            model_name='departamento',
            name='local',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
