# Generated by Django 3.2.4 on 2021-08-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0004_auto_20210801_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local',
        ),
    ]
