# Generated by Django 3.2.4 on 2021-08-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0005_delete_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='nom_local',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
