# Generated by Django 3.2.4 on 2021-08-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0006_proyecto_nom_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='relacion',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
