# Generated by Django 3.2.4 on 2021-08-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0008_proyecto_nombre_proyecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empleados_proyecto',
        ),
    ]
