# Generated by Django 3.2.4 on 2021-08-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0009_delete_empleados_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='local',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='relacion',
        ),
    ]
