# Generated by Django 3.2.4 on 2021-08-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0010_auto_20210804_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependiente',
            old_name='relacion',
            new_name='empleado_encargado',
        ),
        migrations.RemoveField(
            model_name='dependiente',
            name='rfc_empleado',
        ),
    ]
