# Generated by Django 3.2.4 on 2021-08-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0011_auto_20210804_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='nom_dep',
        ),
    ]
