# Generated by Django 3.2.4 on 2021-08-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0012_remove_proyecto_nom_dep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='nombre',
            new_name='nombre_emp',
        ),
    ]
