# Generated by Django 3.2.4 on 2021-08-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0013_rename_nombre_empleado_nombre_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ProyectoGSW.departamento'),
            preserve_default=False,
        ),
    ]
