# Generated by Django 3.2.4 on 2021-08-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0016_rename_dep_empleado_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
    ]
