# Generated by Django 3.2.4 on 2021-08-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0020_empleado_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
    ]
