# Generated by Django 3.2.4 on 2021-08-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0022_empleado_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependiente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='dependiente',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoGSW.empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoGSW.departamento'),
            preserve_default=False,
        ),
    ]
