# Generated by Django 3.2.4 on 2021-08-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0023_auto_20210808_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependiente',
            name='empleado',
        ),
        migrations.AddField(
            model_name='dependiente',
            name='nombre',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
