# Generated by Django 3.2.4 on 2021-08-09 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0025_alter_dependiente_empleado_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='nombre',
        ),
    ]
