# Generated by Django 3.2.4 on 2021-08-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0029_auto_20210808_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependiente',
            name='empleado_encargado',
            field=models.CharField(max_length=30),
        ),
    ]
