# Generated by Django 3.2.4 on 2021-08-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0030_alter_dependiente_empleado_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='dependiente',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rfc',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='nom_persona',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='nom_usuario',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nom_local',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='rfc',
            field=models.IntegerField(unique=True),
        ),
    ]
