# Generated by Django 3.2.4 on 2021-08-09 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0031_auto_20210808_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependiente',
            name='empleado_encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGSW.empleado'),
        ),
    ]
