# Generated by Django 3.2.4 on 2021-08-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGSW', '0032_alter_dependiente_empleado_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='rfc',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
